### PR TITLE
Add correct exports

### LINKED ISSUE #5: Typings not found
```
Could not find a declaration file for module '@kinescope/react-kinescope-player'. '/project-path/node_modules/.pnpm/@kinescope+react-kinescope-player@0.4.1_react-dom@18.2.0_react@18.2.0/node_modules/@kinescope/react-kinescope-player/dist/player.modern.js' implicitly has an 'any' type.
  There are types at '/project-path/node_modules/@kinescope/react-kinescope-player/dist/player.d.ts', but this result could not be resolved when respecting package.json "exports". The '@kinescope/react-kinescope-player' library may need to update its package.json or typings.ts(7016)
```

- typescript 5.2.2
- nextjs 13.5.1
- macos sonoma

### PR DESCRIPTION
**Pull request by sergeysova**
Fixes #5

### CODE REVIEW

**Comment by sergeysova** [comment]
@pushpush Would you like to review and merge?
I am using the fork with this fix (https://npmjs.com/@sergeysova/react-kinescope-player), it works correctly

**Comment by sergeysova** [comment]
Why closed?

**Comment by sergeysova** [comment]
Removed ownership of commits?

https://github.com/kinescope/react-kinescope-player/commit/ed0e78022e0ca959db15ca48bdbfc2d7d4d1763f

**Comment by pushpush** [comment]
> [ed0e780](https://github.com/kinescope/react-kinescope-player/commit/ed0e78022e0ca959db15ca48bdbfc2d7d4d1763f)

Sorry. I pressed the wrong button. I don't understand how to roll back.

**Comment by pushpush** [comment]
Sorry. I pressed the wrong button. I don't understand how to roll back.

**Pull request merged**
